sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Liangqizhe73@
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMvms1M49JQvgbcxTRa
    access-key-secret: 1MWfNO3z6CHlDACP3Vv1FYqHDrlJox
    bucket-name: sky-take-out-7447
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx1fb5597b321200d0
    secret: ef86ba505c637653b2264881ce17d940